### ISSUE TITLE
No substitutions are made on Wikipedia pages

### ISSUE THREAD

**Issue by beszel** [glam-lab/degender-the-web#57]
**Describe the bug**
The plugin performs no substitution on Wikipedia pages that contain gendered pronouns and don't discuss gender. The header incorrectly claims that the page has no gendered pronouns.

**To Reproduce**
Go to [any Wikipedia page](https://en.wikipedia.org/wiki/China_Mi%C3%A9ville) with gendered pronouns that doesn't discuss gender.

**Expected behavior**
The header should indicate that the gendered pronouns have been replaced, as usual. The pronouns themselves should be replaced.

**Additional context**
[Pages that discuss gender](https://en.wikipedia.org/wiki/Ezra_Furman) get the correct header, saying that no pronouns have been replaced.

Substitutions are still made on the Wikipedia home page.

**Comment by ProfJanetDavis** [comment]
@irhawk you are absolutely right! That is so strange, especially since all the text is static and not loaded by a script.

Here's the problem: The paragraphs using gender pronouns are (of course) nested inside the page body. The body element has the style class ```mw-editable```, so the script thinks the entire page content is editable by the user, when it actually is not (at least not as presented by default). I can think of several different ways to approach this. Let me investigate more and think it over.
